baseURL = "https://abhisheksarmah.dev"
languageCode = "en-us"
title = "Abhishek Sarmah - Fullstack web developer, open-source maintainer, blogger"

enableEmoji = true

[markup]
  [markup.highlight]
    noClasses = true
    style = "solarized-dark"
  [markup.goldmark.renderer]
      unsafe = true